# Variables
app    := "app"
bin    := if os_family() == "windows" { app + ".exe" } else { "./" + app }
linter := (if os_family() == "windows" { env_var("USERPROFILE") } else { env_var("HOME") }) + "/go/bin/golangci-lint"

# Default: List all recipes
default:
    @just --list

# Run directly
run:
    go run main.go

# Format and tidy dependencies
fmt:
    go fmt ./...
    go mod tidy

# Lint using golangci-lint
lint:
    @echo "Linting project..."
    "{{linter}}" run ./...

# Build for the current machine
build:
    @echo "Building for {{os()}} {{arch()}}..."
    go build -o {{if os_family() == "windows" { app + ".exe" } else { app }}} main.go

# Build and start the binary
start: build
    {{bin}}

# Clean build artifacts
clean:
    go clean
    rm -f {{app}} {{app}}.exe
