export { default as commentRouter } from "./comment.routes.js";
export { default as dashboardRouter } from "./dashboard.routes.js";
export { default as healthcheckRouter } from "./healthcheck.routes.js";
export { default as likeRouter } from "./like.routes.js";
export { default as playlistRouter } from "./playlist.routes.js";
export { default as postRouter } from "./post.routes.js";
export { default as subscriptionRouter } from "./subscription.routes.js";
export { default as userRouter } from "./user.routes.js";
export { default as videoRouter } from "./video.routes.js";
